services:
    alg.forumticket.listener:
        class: alg\forumticket\event\listener
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@auth'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@request'
            - '@pagination'
        tags:
            - { name: event.listener }
